spring:
  datasource:
    url: jdbc:h2:mem:sms
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
          trace: false
          web-allow-others: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: "/admin/swagger-ui"
  packagesToScan: "com.paremskis.sms"
  pathsToMatch: /**

management:
  server:
    port: 8001

server:
  port: 8000

app:
  config:
    test-prop: "testValue"